name: CI

on:
  push:
    branches: 
      - master

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup Elm environment
        uses: JorelAli/setup-elm@v1
        with:
          elm-version: 0.19.1
      - name: Basic Testing
        run: ls
      - name: Compile Elm Files
        run: make optimized
      - name: GitHub Pages Deploy
        uses: maxheld83/ghpages@v0.2.1
        if: success() && github.event == 'push' && github.ref == 'master'
        env:
          BUILD_DIR: dist/
